[package]
name = "RoguelikeAgain"
version = "0.1.0"
edition = "2024"
resolver = "2"

[dependencies]
doryen-rs = "1.3.0"
hecs = "0.10.5"
rand = "0.9.2"
tracing = { version = "0.1.41", features = ["log", "max_level_debug"] }
tracing-subscriber = "0.3.20"